require("dotenv").config({ quiet: true });
import { Request, Response, NextFunction } from "express";
import ErrorHandler from "../utils/Errorhandler";
import { CatchAsyncError } from "../middleware/CatchAsyncErrors";
import { logger } from "../utils/logger";
import cron from "node-cron";

import {
  ExpenseDeleteService,
  ExpenseFetchService,
  ExpenseGenerationService,
  ExpensesEditService,
  PermanentExpenseDeletionService,
} from "../services/expenses.services";

export const ExpensesGenerationController = CatchAsyncError(
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      await ExpenseGenerationService(req.body);
      res.status(200).json({
        success: true,
        message: `New expense generated`,
      });
      logger.info(`New expense generated by user: ${req.user?.user_id}`);
    } catch (error: any) {
      if (error) {
        return next(new ErrorHandler(error.message, 500));
      }
    }
  }
);

export const ExpensesFetchController = CatchAsyncError(
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const expenseData = await ExpenseFetchService();
      res.status(200).json({
        success: true,
        expenses: expenseData,
        message: `Expense data fetched`,
      });
      logger.info(`Expense data fetched by user: ${req.user?.user_id}`);
    } catch (error: any) {
      if (error) {
        return next(new ErrorHandler(error.message, 500));
      }
    }
  }
);

export const ExpensesEditController = CatchAsyncError(
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      await ExpensesEditService(req.body);
      res.status(200).json({
        success: true,
        message: `Expense successfully edited`,
      });
      logger.info(
        `Expense:${req.body.expense_id} successfully edited by: ${req.user?.user_id}`
      );
    } catch (error: any) {
      if (error) {
        return next(new ErrorHandler(error.message, 500));
      }
    }
  }
);

export const ExpenseDeleteController = CatchAsyncError(
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { expense_id } = req.params;
      await ExpenseDeleteService(expense_id);
      res.status(200).json({
        success: true,
        message: `Expense: ${expense_id} deleted successfully`,
      });
      logger.info(
        `Expense: ${expense_id} deleted successfully by: ${req.user?.user_id}`
      );
    } catch (error: any) {
      if (error) {
        return next(new ErrorHandler(error.message, 500));
      }
    }
  }
);

cron.schedule("0 0 * * *", async () => {
  await PermanentExpenseDeletionService();
  logger.info("Removing deleted expenses", {
    action: "Expense deletion",
    status: "success",
  });
  console.log("_____________");
  console.log("running cron: removing deleted expenses");
});
